Repository rancher/elemental-toolkit, pull requests merged in 2021-09, with the labels that each got.

#606 grub-artifacts: add provides to respect old packages
  packages/grub2/collection.yaml
Labels: bug

#621 arm64: add missing grub package
  packages/grub2/build.yaml
  packages/livecd/grub2/build.yaml
  values/green-arm64.yaml
Labels: arm64

#629 ci: enable manifest and luet repo for arm64
  .github/config/master.yaml
  .github/config/pr.yaml
  .github/config/releases.yaml
  .github/workflows/build-master-arm64.yaml
  .github/workflows/build-pr-arm64.yaml
  .github/workflows/build-releases-arm64.yaml
Labels: arm64

#669 ci: publish arm64 toolchain
  .github/build.yaml.gomplate
  .github/config/master.yaml
  .github/config/releases.yaml
  .github/workflows/build-master-arm64.yaml
  .github/workflows/build-master-x86_64.yaml
  .github/workflows/build-releases-arm64.yaml
  .github/workflows/build-releases-x86_64.yaml
Labels: blocked

#666 jq: build arm64 version
  packages/utils/jq/build.yaml
  packages/utils/jq/definition.yaml
Labels: arm64

#715 Update packages badge in README
  README.md
Labels: Do not merge

#711 Iso arm64
  .github/build.yaml.gomplate
  .github/config/examples.yaml
  .github/config/master.yaml
  .github/config/nightly.yaml
  .github/config/pr-docker.yaml
  .github/config/pr.yaml
  .github/config/releases.yaml
  .github/workflows/build-master-arm64.yaml
  .github/workflows/build-master-x86_64.yaml
  .github/workflows/build-nightly-x86_64.yaml
  .github/workflows/build-pr-arm64.yaml
  .github/workflows/build-pr-x86_64.yaml
  .github/workflows/build-releases-arm64.yaml
  .github/workflows/build-releases-x86_64.yaml
  Makefile
  packages/cos/collection.yaml
  packages/kernel/build.yaml
  packages/kernel/definition.yaml
  packages/livecd/grub2/build.yaml
  packages/livecd/grub2/collection.yaml
  packages/livecd/grub2/config/grub_live.cfg
  packer/images.json.pkr.hcl
  packer/variables.pkr.hcl
  values/green-arm64.yaml
Labels: arm64

#719 installer: User arch variables for installation
  packages/cos/collection.yaml
  packages/installer/definition.yaml
  packages/installer/installer.sh
  packages/installer/reset.sh
  packages/installer/upgrade.sh
Labels: arm64

#717 Img builder arm64
  .github/build.yaml.gomplate
  .github/config/examples.yaml
  .github/config/master.yaml
  .github/config/nightly.yaml
  .github/config/pr-docker.yaml
  .github/config/pr.yaml
  .github/config/releases.yaml
  .github/workflows/build-master-green-arm64.yaml
  .github/workflows/build-pr-green-arm64.yaml
  .github/workflows/build-releases-green-arm64.yaml
Labels: arm64

#735 Raw image arm64
  .github/build.yaml.gomplate
  .github/workflows/build-master-green-arm64.yaml
  .github/workflows/build-master-green-x86_64.yaml
  .github/workflows/build-nightly-blue-x86_64.yaml
  .github/workflows/build-nightly-green-x86_64.yaml
  .github/workflows/build-nightly-orange-x86_64.yaml
  .github/workflows/build-pr-green-arm64.yaml
  .github/workflows/build-pr-green-x86_64.yaml
  .github/workflows/build-releases-green-arm64.yaml
  .github/workflows/build-releases-green-x86_64.yaml
  images/img-builder.sh
  manifest.yaml
Labels: arm64

#736 ci: enable qemu packer building on arm64
  .github/build.yaml.gomplate
  .github/config/pr.yaml
  .github/workflows/build-master-green-x86_64.yaml
  .github/workflows/build-nightly-green-x86_64.yaml
  .github/workflows/build-pr-green-arm64.yaml
  .github/workflows/build-pr-green-x86_64.yaml
  .github/workflows/build-releases-green-x86_64.yaml
  packer/images.json.pkr.hcl
  packer/variables.pkr.hcl
Labels: arm64

#740 make: fix FINAL_REPO order
  Makefile
Labels: bug

#739 immutable-rootfs: add newer packages for fs expansion
  packages/cos/collection.yaml
  packages/immutable-rootfs/30cos-immutable-rootfs/module-setup.sh
  packages/immutable-rootfs/definition.yaml
  packages/initrd/definition.yaml
  packages/meta/collection.yaml
  packages/toolchain/collection.yaml
Labels: blocked
