Repository rancher/elemental-toolkit, pull requests merged in 2022-05, with the labels that each got.

#1289 Do not add final repo for local-iso build target
  .github/build.yaml.gomplate
  .github/workflows/build-master-green-arm64.yaml
  .github/workflows/build-master-green-x86_64.yaml
  .github/workflows/build-nightly-green-x86_64.yaml
  .github/workflows/build-pr-green-arm64.yaml
  .github/workflows/build-pr-green-x86_64.yaml
  .github/workflows/build-releases-green-arm64.yaml
  .github/workflows/build-releases-green-x86_64.yaml
Labels: arm64

#1284 Install deps before adding local repo
  .github/build.yaml.gomplate
  .github/workflows/build-master-green-arm64.yaml
  .github/workflows/build-master-green-x86_64.yaml
  .github/workflows/build-nightly-green-x86_64.yaml
  .github/workflows/build-pr-green-arm64.yaml
  .github/workflows/build-pr-green-x86_64.yaml
  .github/workflows/build-releases-green-arm64.yaml
  .github/workflows/build-releases-green-x86_64.yaml
Labels: arm64

#1293 Fix PACKAGES selection from makefile
  make/Makefile.build
  make/Makefile.iso
Labels: arm64

#1316 Expand development.md
  DEVELOPMENT.md
Labels: documentation

#1320 Fix tag and tag pushing for autorelease
  .github/workflows/autorelease.yaml
Labels: bug, automation

#1340 Fix yq stanza for generating repo files
  .github/build.yaml.gomplate
  .github/workflows/build-releases-green-arm64.yaml
  .github/workflows/build-releases-green-x86_64.yaml
Labels: bug, automation

#1358 Revert tool_image change to tumbleweed
  values/blue-arm64.yaml
  values/blue-x86_64.yaml
  values/green-arm64.yaml
  values/green-x86_64.yaml
  values/orange-arm64.yaml
  values/orange-x86_64.yaml
Labels: arm64

#1354 Fix package names on rpi/odroid docker builds
  .github/workflows/multi-arch-embedded-devices-examples.yaml
  examples/odroid-c2-leap/Dockerfile
  examples/odroid-c2-leap/conf/luet.yaml
  examples/odroid-c2-leap/files/etc/cos/bootargs.cfg
  examples/odroid-c2-leap/files/etc/cos/config
  examples/odroid-c2-leap/files/etc/os-release
  examples/odroid-c2-leap/files/system/oem/01_auto_expand.yaml
  examples/odroid-c2-leap/files/system/oem/01_layout.yaml
  examples/odroid-c2-leap/files/system/oem/04_accounting.yaml
  examples/odroid-c2/Dockerfile
  examples/rpi-leap/Dockerfile
  examples/rpi-leap/conf/luet.yaml
  examples/rpi-leap/files/etc/cos/bootargs.cfg
  examples/rpi-leap/files/etc/cos/config
  examples/rpi-leap/files/etc/os-release
  examples/rpi-leap/files/system/oem/01_auto_expand.yaml
  examples/rpi-leap/files/system/oem/01_layout.yaml
  examples/rpi-leap/files/system/oem/04_accounting.yaml
  examples/rpi/Dockerfile
Labels: blocked

#1373 Bump cos and test helpers to fix arm64
  packages/cos/collection.yaml
  tests/go.mod
  tests/go.sum
  tests/upgrades-images-unsigned/upgrade_test.go
Labels: arm64
