Repository rancher/elemental-toolkit, pull requests merged in 2023-12, with the labels that each got.

#1869 Fix initrd and kernel ISO paths
  pkg/constants/constants.go
Labels: kind/bug

#1873 Add force flag in systemd-firstboot yip's plugin
  examples/blue/Dockerfile
  examples/orange/Dockerfile
  pkg/features/embedded/cloud-config-defaults/system/oem/01_defaults.yaml
Labels: all-distros

#1866 Refactor early system mounting
  .gitignore
  Dockerfile
  Makefile
  cmd/config/config.go
  cmd/mount.go
  config.yaml.example
  examples/green/Dockerfile
  examples/tumbleweed/Dockerfile
  go.mod
  go.sum
  pkg/action/build-disk.go
  pkg/action/mount.go
  pkg/action/mount_test.go
  pkg/action/upgrade.go
  pkg/action/upgrade_test.go
  pkg/config/config.go
  pkg/constants/constants.go
  pkg/elemental/elemental.go
  pkg/elemental/elemental_test.go
  pkg/features/embedded/cloud-config-defaults/system/oem/03_branding.yaml
  pkg/features/embedded/cloud-config-essentials/system/oem/00_rootfs.yaml
  pkg/features/embedded/cloud-config-essentials/system/oem/06_recovery.yaml
  pkg/features/embedded/cloud-config-essentials/system/oem/07_live.yaml
  pkg/features/embedded/cloud-config-essentials/system/oem/08_boot_assessment.yaml
  pkg/features/embedded/elemental-rootfs/etc/dracut.conf.d/02-elemental-rootfs.conf
  pkg/features/embedded/elemental-rootfs/usr/lib/dracut/modules.d/30elemental-rootfs/module-setup.sh
  pkg/features/embedded/elemental-rootfs/usr/lib/systemd/system/elemental-rootfs.service
  pkg/features/embedded/elemental-setup/etc/dracut.conf.d/02-elemental-setup.conf
  pkg/features/embedded/elemental-setup/usr/lib/dracut/modules.d/10elemental-setup/module-setup.sh
  pkg/features/embedded/elemental-setup/usr/lib/dracut/modules.d/10elemental-setup/oem-generator.sh
  pkg/features/embedded/elemental-setup/usr/lib/systemd/system/elemental-setup-rootfs.service
  pkg/features/embedded/elemental-sysroot/etc/dracut.conf.d/03-elemental-sysroot.conf
  pkg/features/embedded/elemental-sysroot/usr/lib/dracut/modules.d/20elemental-sysroot/elemental-cmdline.sh
  pkg/features/embedded/elemental-sysroot/usr/lib/dracut/modules.d/20elemental-sysroot/elemental-fsck.sh
  pkg/features/embedded/elemental-sysroot/usr/lib/dracut/modules.d/20elemental-sysroot/module-setup.sh
  pkg/features/embedded/elemental-sysroot/usr/lib/dracut/modules.d/20elemental-sysroot/sysroot-generator.sh
  pkg/features/embedded/grub-config/etc/cos/grub.cfg
  pkg/features/embedded/grub-default-bootargs/etc/cos/bootargs.cfg
  pkg/features/embedded/immutable-rootfs/usr/lib/dracut/modules.d/30elemental-immutable-rootfs/elemental-generator.sh
  pkg/features/embedded/immutable-rootfs/usr/lib/dracut/modules.d/30elemental-immutable-rootfs/parse-elemental-cmdline.sh
  pkg/features/features.go
  pkg/systemd/unit.go
  pkg/types/v1/config.go
  pkg/utils/common.go
  pkg/utils/utils_test.go
  scripts/run_vm.sh
  tests/fallback/fallback_test.go
  tests/grubfallback/grubfallback_test.go
  vendor/github.com/rancher-sandbox/ele-testhelpers/vm/sut.go
  vendor/modules.txt
Labels: kind/enhancement, area/elemental-cli, area/boot
